engines:
  rubocop:
    enabled: true
    channel: rubocop-1-4-1
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 60
ratings:
  paths:
    - lib/**
exclude_paths:
  - spec/**/*
