require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
  - vendor/**/*
  - tmp/**/*

inherit_from:
  - ./rubocop/rubocop-layout.yml
  - ./rubocop/rubocop-styles.yml
  - ./rubocop/rubocop-lint.yml
  - ./rubocop/rubocop-metric.yml
  - ./rubocop/rubocop-naming.yml
  - ./rubocop/rubocop-performance.yml
